#include "platform\windows\KeyCodeTranslator_win32.hpp"

#include <Windows.h>

namespace silver::core
{
	std::map<const unsigned int, KeyCode> KeyCodeTranslator_win32::database_
	{
		{ VK_NONAME, KeyCode::KEY_NO_CODE },

		{ 0x41, KeyCode::KEY_A },
		{ 0x42, KeyCode::KEY_B },
		{ 0x43, KeyCode::KEY_C },
		{ 0x44, KeyCode::KEY_D },
		{ 0x45, KeyCode::KEY_E },
		{ 0x46, KeyCode::KEY_F },
		{ 0x47, KeyCode::KEY_G },
		{ 0x48, KeyCode::KEY_H },
		{ 0x49, KeyCode::KEY_I },
		{ 0x4A, KeyCode::KEY_J },
		{ 0x4B, KeyCode::KEY_K },
		{ 0x4C, KeyCode::KEY_L },
		{ 0x4D, KeyCode::KEY_M },
		{ 0x4E, KeyCode::KEY_N },
		{ 0x4F, KeyCode::KEY_O },
		{ 0x50, KeyCode::KEY_P },
		{ 0x51, KeyCode::KEY_Q },
		{ 0x52, KeyCode::KEY_R },
		{ 0x53, KeyCode::KEY_S },
		{ 0x54, KeyCode::KEY_T },
		{ 0x55, KeyCode::KEY_U },
		{ 0x56, KeyCode::KEY_V },
		{ 0x57, KeyCode::KEY_W },
		{ 0x58, KeyCode::KEY_X },
		{ 0x59, KeyCode::KEY_Y },
		{ 0x5A, KeyCode::KEY_Z },

		{ 0x30, KeyCode::KEY_0 },
		{ 0x31, KeyCode::KEY_1 },
		{ 0x32, KeyCode::KEY_2 },
		{ 0x33, KeyCode::KEY_3 },
		{ 0x34, KeyCode::KEY_4 },
		{ 0x35, KeyCode::KEY_5 },
		{ 0x36, KeyCode::KEY_6 },
		{ 0x37, KeyCode::KEY_7 },
		{ 0x38, KeyCode::KEY_8 },
		{ 0x39, KeyCode::KEY_9 },

		{ VK_F1, KeyCode::KEY_F1 },
		{ VK_F2, KeyCode::KEY_F2 },
		{ VK_F3, KeyCode::KEY_F3 },
		{ VK_F4, KeyCode::KEY_F4 },
		{ VK_F5, KeyCode::KEY_F5 },
		{ VK_F6, KeyCode::KEY_F6 },
		{ VK_F7, KeyCode::KEY_F7 },
		{ VK_F8, KeyCode::KEY_F8 },
		{ VK_F9, KeyCode::KEY_F9 },
		{ VK_F10, KeyCode::KEY_F10 },
		{ VK_F11, KeyCode::KEY_F11 },
		{ VK_F12, KeyCode::KEY_F12 },
		{ VK_F13, KeyCode::KEY_F13 },
		{ VK_F14, KeyCode::KEY_F14 },
		{ VK_F15, KeyCode::KEY_F15 },
		{ VK_F16, KeyCode::KEY_F16 },
		{ VK_F17, KeyCode::KEY_F17 },
		{ VK_F18, KeyCode::KEY_F18 },
		{ VK_F19, KeyCode::KEY_F19 },
		{ VK_F20, KeyCode::KEY_F20 },
		{ VK_F21, KeyCode::KEY_F21 },
		{ VK_F22, KeyCode::KEY_F22 },
		{ VK_F23, KeyCode::KEY_F23 },
		{ VK_F24, KeyCode::KEY_F24 },

		{ VK_NUMPAD0, KeyCode::KEY_NUM0 },
		{ VK_NUMPAD1, KeyCode::KEY_NUM1 },
		{ VK_NUMPAD2, KeyCode::KEY_NUM2 },
		{ VK_NUMPAD3, KeyCode::KEY_NUM3 },
		{ VK_NUMPAD4, KeyCode::KEY_NUM4 },
		{ VK_NUMPAD5, KeyCode::KEY_NUM5 },
		{ VK_NUMPAD6, KeyCode::KEY_NUM6 },
		{ VK_NUMPAD7, KeyCode::KEY_NUM7 },
		{ VK_NUMPAD8, KeyCode::KEY_NUM8 },
		{ VK_NUMPAD9, KeyCode::KEY_NUM9 },

		{ VK_MULTIPLY, KeyCode::KEY_NUMMULTIPLY },
		{ VK_DIVIDE, KeyCode::KEY_NUMDIVIDE },
		{ VK_ADD, KeyCode::KEY_NUMADD },
		{ VK_SUBTRACT, KeyCode::KEY_NUMSUBTRACT },

		{ VK_BACK, KeyCode::KEY_BACKSPACE },
		{ VK_TAB, KeyCode::KEY_TAB },
		{ VK_SPACE, KeyCode::KEY_SPACE },
		{ VK_RETURN, KeyCode::KEY_ENTER },
		{ VK_CLEAR, KeyCode::KEY_CLEAR },
		{ VK_PAUSE, KeyCode::KEY_PAUSE },
		{ VK_ESCAPE, KeyCode::KEY_ESCAPE },

		{ VK_PRIOR, KeyCode::KEY_PAGEUP },
		{ VK_NEXT, KeyCode::KEY_PAGEDOWN },
		{ VK_END, KeyCode::KEY_END },
		{ VK_HOME, KeyCode::KEY_HOME },
		{ VK_INSERT, KeyCode::KEY_INSERT },
		{ VK_DELETE, KeyCode::KEY_DELETE },
		{ VK_MULTIPLY, KeyCode::KEY_MULTIPLY },
		{ VK_DIVIDE, KeyCode::KEY_DIVIDE },
		{ VK_ADD, KeyCode::KEY_ADD },
		{ VK_SUBTRACT, KeyCode::KEY_SUBTRACT },
		{ VK_SEPARATOR, KeyCode::KEY_SEPARATOR },
		{ VK_DECIMAL, KeyCode::KEY_DECIMAL },

		{ VK_UP, KeyCode::KEY_UP },
		{ VK_DOWN, KeyCode::KEY_DOWN },
		{ VK_LEFT, KeyCode::KEY_LEFT },
		{ VK_RIGHT, KeyCode::KEY_RIGHT },

		{ VK_SELECT, KeyCode::KEY_SELECT },
		{ VK_PRINT, KeyCode::KEY_PRINTSCREEN },
		{ VK_EXECUTE, KeyCode::KEY_EXE },
		{ VK_SNAPSHOT, KeyCode::KEY_SNAPSHOT },
		{ VK_HELP, KeyCode::KEY_HELP },
		{ VK_SLEEP, KeyCode::KEY_SLEEP },

		{ VK_SCROLL, KeyCode::KEY_SCROLLLOCK },
		{ VK_CAPITAL, KeyCode::KEY_CAPSLOCK },

		{ VK_OEM_NEC_EQUAL, KeyCode::KEY_OEM_NUMEQUAL },
		{ VK_OEM_FJ_JISHO, KeyCode::KEY_OEM_DICTIONARY },
		{ VK_OEM_FJ_MASSHOU, KeyCode::KEY_OEM_UNREGISTER },
		{ VK_OEM_FJ_TOUROKU, KeyCode::KEY_OEM_REGISTER },
		{ VK_OEM_FJ_LOYA, KeyCode::KEY_OEM_LOYAYUBI },
		{ VK_OEM_FJ_ROYA, KeyCode::KEY_OEM_ROYAYUBI },
		{ VK_OEM_PLUS, KeyCode::KEY_OEM_PLUS },
		{ VK_OEM_COMMA, KeyCode::KEY_OEM_COMMA },
		{ VK_OEM_MINUS, KeyCode::KEY_OEM_MINUS },
		{ VK_OEM_PERIOD, KeyCode::KEY_OEM_PERIOD },
		{ VK_OEM_1, KeyCode::KEY_OEM1 },
		{ VK_OEM_2, KeyCode::KEY_OEM2 },
		{ VK_OEM_3, KeyCode::KEY_OEM3 },
		{ VK_OEM_4, KeyCode::KEY_OEM4 },
		{ VK_OEM_5, KeyCode::KEY_OEM5 },
		{ VK_OEM_6, KeyCode::KEY_OEM6 },
		{ VK_OEM_7, KeyCode::KEY_OEM7 },
		{ VK_OEM_8, KeyCode::KEY_OEM8 },
		{ VK_OEM_AX, KeyCode::KEY_OEM_AX },
		{ VK_OEM_102, KeyCode::KEY_OEM102 },

		{ VK_BROWSER_BACK, KeyCode::KEY_BROWSER_BACK },
		{ VK_BROWSER_FORWARD, KeyCode::KEY_BROWSER_FORWARD },
		{ VK_BROWSER_REFRESH, KeyCode::KEY_BROWSER_REFRESH },
		{ VK_BROWSER_STOP, KeyCode::KEY_BROWSER_STOP },
		{ VK_BROWSER_SEARCH, KeyCode::KEY_BROWSER_SEARCH },
		{ VK_BROWSER_FAVORITES, KeyCode::KEY_BROWSER_FAVORITE },
		{ VK_BROWSER_HOME, KeyCode::KEY_BROWSER_HOME },

		{ VK_VOLUME_UP, KeyCode::KEY_VOLUME_UP },
		{ VK_VOLUME_DOWN, KeyCode::KEY_VOLUME_DOWN },
		{ VK_VOLUME_MUTE, KeyCode::KEY_VOLUME_MUTE },

		{ VK_MEDIA_NEXT_TRACK, KeyCode::KEY_MEDIA_NEXT },
		{ VK_MEDIA_PREV_TRACK, KeyCode::KEY_MEDIA_PREV },
		{ VK_MEDIA_STOP, KeyCode::KEY_MEDIA_STOP },
		{ VK_MEDIA_PLAY_PAUSE, KeyCode::KEY_MEDIA_PLAY_PAUSE },
		{ VK_LAUNCH_MEDIA_SELECT, KeyCode::KEY_MEDIA_SELECT },

		{ VK_LAUNCH_APP1,  KeyCode::KEY_LAUNCH_APP1 },
		{ VK_LAUNCH_APP2, KeyCode::KEY_LAUNCH_APP2 },
		{ VK_LAUNCH_MAIL, KeyCode::KEY_LAUNCH_MAIL },

		{ VK_APPS, KeyCode::KEY_APPLICATION },

		{ VK_RSHIFT, KeyCode::KEY_RSHIFT },
		{ VK_RMENU, KeyCode::KEY_RALT },
		{ VK_RCONTROL, KeyCode::KEY_RCTRL },
		{ VK_RWIN, KeyCode::KEY_RWIN },
		{ VK_LSHIFT, KeyCode::KEY_LSHIFT },
		{ VK_LMENU, KeyCode::KEY_LALT },
		{ VK_LWIN, KeyCode::KEY_LWIN },

		{ VK_SHIFT, KeyCode::KEY_SHIFT },
		{ VK_MENU, KeyCode::KEY_ALT },
		{ VK_CONTROL, KeyCode::KEY_CTRL },
	};

	KeyCode KeyCodeTranslator_win32::translate(const unsigned int key) noexcept
	{
		return database_[key];
	}
}